# generated by datamodel-codegen:
#   filename:  schema.graphql
#   timestamp: 2025-05-16T00:50:27+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, TypeAlias

from pydantic import BaseModel, Field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Date: TypeAlias = str


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


Upload: TypeAlias = str
"""
The `Upload` scalar type represents a file upload.
"""


class AssetKind(Enum):
    ALL = 'ALL'
    BINARY = 'BINARY'
    IMAGE = 'IMAGE'


class CacheControlScope(Enum):
    PRIVATE = 'PRIVATE'
    PUBLIC = 'PUBLIC'


class NavigationMode(Enum):
    MIXED = 'MIXED'
    NONE = 'NONE'
    STATIC = 'STATIC'
    TREE = 'TREE'


class PageOrderBy(Enum):
    CREATED = 'CREATED'
    ID = 'ID'
    PATH = 'PATH'
    TITLE = 'TITLE'
    UPDATED = 'UPDATED'


class PageOrderByDirection(Enum):
    ASC = 'ASC'
    DESC = 'DESC'


class PageRuleMatch(Enum):
    END = 'END'
    EXACT = 'EXACT'
    REGEX = 'REGEX'
    START = 'START'
    TAG = 'TAG'


class PageTreeMode(Enum):
    ALL = 'ALL'
    FOLDERS = 'FOLDERS'
    PAGES = 'PAGES'


class SystemImportUsersGroupMode(Enum):
    MULTI = 'MULTI'
    NONE = 'NONE'
    SINGLE = 'SINGLE'


class AnalyticsMutation(BaseModel):
    """
    Mutations for Analytics
    """

    updateProviders: Optional[DefaultResponse] = Field(
        None, description='Update a list of Analytics providers and their configuration'
    )
    typename__: Optional[Literal['AnalyticsMutation']] = Field(
        'AnalyticsMutation', alias='__typename'
    )


class AnalyticsProvider(BaseModel):
    """
    Analytics Provider
    """

    config: Optional[List[Optional[KeyValuePair]]] = Field(
        None, description='Configuration values for this provider'
    )
    description: Optional[String] = Field(
        None, description='Short description of the provider'
    )
    isAvailable: Optional[Boolean] = Field(
        None, description='Is the provider available for use'
    )
    isEnabled: Boolean = Field(..., description='Is the provider active')
    key: String = Field(..., description='Unique identifier for this provider')
    logo: Optional[String] = Field(None, description='Path to the provider logo')
    props: Optional[List[Optional[String]]] = Field(
        None,
        description='List of configuration properties, formatted as stringified JSON objects',
    )
    title: String = Field(..., description='Name of the provider')
    website: Optional[String] = Field(None, description='Website of the provider')
    typename__: Optional[Literal['AnalyticsProvider']] = Field(
        'AnalyticsProvider', alias='__typename'
    )


class AnalyticsQuery(BaseModel):
    """
    Queries for Analytics
    """

    providers: Optional[List[Optional[AnalyticsProvider]]] = Field(
        None, description='Fetch list of Analytics providers and their configuration'
    )
    typename__: Optional[Literal['AnalyticsQuery']] = Field(
        'AnalyticsQuery', alias='__typename'
    )


class AssetFolder(BaseModel):
    id: Int
    name: Optional[String] = None
    slug: String
    typename__: Optional[Literal['AssetFolder']] = Field(
        'AssetFolder', alias='__typename'
    )


class AssetItem(BaseModel):
    author: Optional[User] = None
    createdAt: Date
    ext: String
    fileSize: Int
    filename: String
    folder: Optional[AssetFolder] = None
    id: Int
    kind: AssetKind
    metadata: Optional[String] = None
    mime: String
    updatedAt: Date
    typename__: Optional[Literal['AssetItem']] = Field('AssetItem', alias='__typename')


class AssetMutation(BaseModel):
    createFolder: Optional[DefaultResponse] = None
    deleteAsset: Optional[DefaultResponse] = None
    flushTempUploads: Optional[DefaultResponse] = None
    renameAsset: Optional[DefaultResponse] = None
    typename__: Optional[Literal['AssetMutation']] = Field(
        'AssetMutation', alias='__typename'
    )


class AssetQuery(BaseModel):
    folders: Optional[List[Optional[AssetFolder]]] = None
    list: Optional[List[Optional[AssetItem]]] = None
    typename__: Optional[Literal['AssetQuery']] = Field(
        'AssetQuery', alias='__typename'
    )


class AuthenticationActiveStrategy(BaseModel):
    autoEnrollGroups: List[Optional[Int]]
    config: Optional[List[Optional[KeyValuePair]]] = None
    displayName: String
    domainWhitelist: List[Optional[String]]
    isEnabled: Boolean
    key: String
    order: Int
    selfRegistration: Boolean
    strategy: AuthenticationStrategy
    typename__: Optional[Literal['AuthenticationActiveStrategy']] = Field(
        'AuthenticationActiveStrategy', alias='__typename'
    )


class AuthenticationApiKey(BaseModel):
    createdAt: Date
    expiration: Date
    id: Int
    isRevoked: Boolean
    keyShort: String
    name: String
    updatedAt: Date
    typename__: Optional[Literal['AuthenticationApiKey']] = Field(
        'AuthenticationApiKey', alias='__typename'
    )


class AuthenticationCreateApiKeyResponse(BaseModel):
    key: Optional[String] = None
    responseResult: Optional[ResponseStatus] = None
    typename__: Optional[Literal['AuthenticationCreateApiKeyResponse']] = Field(
        'AuthenticationCreateApiKeyResponse', alias='__typename'
    )


class AuthenticationLoginResponse(BaseModel):
    continuationToken: Optional[String] = None
    jwt: Optional[String] = None
    mustChangePwd: Optional[Boolean] = None
    mustProvideTFA: Optional[Boolean] = None
    mustSetupTFA: Optional[Boolean] = None
    redirect: Optional[String] = None
    responseResult: Optional[ResponseStatus] = None
    tfaQRImage: Optional[String] = None
    typename__: Optional[Literal['AuthenticationLoginResponse']] = Field(
        'AuthenticationLoginResponse', alias='__typename'
    )


class AuthenticationMutation(BaseModel):
    createApiKey: Optional[AuthenticationCreateApiKeyResponse] = None
    forgotPassword: Optional[DefaultResponse] = None
    login: Optional[AuthenticationLoginResponse] = None
    loginChangePassword: Optional[AuthenticationLoginResponse] = None
    loginTFA: Optional[AuthenticationLoginResponse] = None
    regenerateCertificates: Optional[DefaultResponse] = None
    register_: Optional[AuthenticationRegisterResponse] = Field(None, alias='register')
    resetGuestUser: Optional[DefaultResponse] = None
    revokeApiKey: Optional[DefaultResponse] = None
    setApiState: Optional[DefaultResponse] = None
    updateStrategies: Optional[DefaultResponse] = None
    typename__: Optional[Literal['AuthenticationMutation']] = Field(
        'AuthenticationMutation', alias='__typename'
    )


class AuthenticationQuery(BaseModel):
    activeStrategies: Optional[List[Optional[AuthenticationActiveStrategy]]] = None
    apiKeys: Optional[List[Optional[AuthenticationApiKey]]] = None
    apiState: Boolean
    strategies: Optional[List[Optional[AuthenticationStrategy]]] = None
    typename__: Optional[Literal['AuthenticationQuery']] = Field(
        'AuthenticationQuery', alias='__typename'
    )


class AuthenticationRegisterResponse(BaseModel):
    jwt: Optional[String] = None
    responseResult: Optional[ResponseStatus] = None
    typename__: Optional[Literal['AuthenticationRegisterResponse']] = Field(
        'AuthenticationRegisterResponse', alias='__typename'
    )


class AuthenticationStrategy(BaseModel):
    color: Optional[String] = None
    description: Optional[String] = None
    icon: Optional[String] = None
    isAvailable: Optional[Boolean] = None
    key: String
    logo: Optional[String] = None
    props: Optional[List[Optional[KeyValuePair]]] = None
    title: String
    useForm: Boolean
    usernameType: Optional[String] = None
    website: Optional[String] = None
    typename__: Optional[Literal['AuthenticationStrategy']] = Field(
        'AuthenticationStrategy', alias='__typename'
    )


class CommentCreateResponse(BaseModel):
    id: Optional[Int] = None
    responseResult: Optional[ResponseStatus] = None
    typename__: Optional[Literal['CommentCreateResponse']] = Field(
        'CommentCreateResponse', alias='__typename'
    )


class CommentMutation(BaseModel):
    create: Optional[CommentCreateResponse] = None
    delete: Optional[DefaultResponse] = None
    update: Optional[CommentUpdateResponse] = None
    updateProviders: Optional[DefaultResponse] = None
    typename__: Optional[Literal['CommentMutation']] = Field(
        'CommentMutation', alias='__typename'
    )


class CommentPost(BaseModel):
    authorEmail: String
    authorIP: String
    authorId: Int
    authorName: String
    content: String
    createdAt: Date
    id: Int
    render: String
    updatedAt: Date
    typename__: Optional[Literal['CommentPost']] = Field(
        'CommentPost', alias='__typename'
    )


class CommentProvider(BaseModel):
    config: Optional[List[Optional[KeyValuePair]]] = None
    description: Optional[String] = None
    isAvailable: Optional[Boolean] = None
    isEnabled: Boolean
    key: String
    logo: Optional[String] = None
    title: String
    website: Optional[String] = None
    typename__: Optional[Literal['CommentProvider']] = Field(
        'CommentProvider', alias='__typename'
    )


class CommentQuery(BaseModel):
    list: List[Optional[CommentPost]]
    providers: Optional[List[Optional[CommentProvider]]] = None
    single: Optional[CommentPost] = None
    typename__: Optional[Literal['CommentQuery']] = Field(
        'CommentQuery', alias='__typename'
    )


class CommentUpdateResponse(BaseModel):
    render: Optional[String] = None
    responseResult: Optional[ResponseStatus] = None
    typename__: Optional[Literal['CommentUpdateResponse']] = Field(
        'CommentUpdateResponse', alias='__typename'
    )


class ContributeContributor(BaseModel):
    avatar: Optional[String] = None
    id: String
    joined: Date
    name: String
    source: String
    twitter: Optional[String] = None
    website: Optional[String] = None
    typename__: Optional[Literal['ContributeContributor']] = Field(
        'ContributeContributor', alias='__typename'
    )


class ContributeQuery(BaseModel):
    contributors: Optional[List[Optional[ContributeContributor]]] = None
    typename__: Optional[Literal['ContributeQuery']] = Field(
        'ContributeQuery', alias='__typename'
    )


class DefaultResponse(BaseModel):
    """
    Generic Mutation Response
    """

    responseResult: Optional[ResponseStatus] = None
    typename__: Optional[Literal['DefaultResponse']] = Field(
        'DefaultResponse', alias='__typename'
    )


class Group(BaseModel):
    createdAt: Date
    id: Int
    isSystem: Boolean
    name: String
    pageRules: Optional[List[Optional[PageRule]]] = None
    permissions: List[Optional[String]]
    redirectOnLogin: Optional[String] = None
    updatedAt: Date
    users: Optional[List[Optional[UserMinimal]]] = None
    typename__: Optional[Literal['Group']] = Field('Group', alias='__typename')


class GroupMinimal(BaseModel):
    createdAt: Date
    id: Int
    isSystem: Boolean
    name: String
    updatedAt: Date
    userCount: Optional[Int] = None
    typename__: Optional[Literal['GroupMinimal']] = Field(
        'GroupMinimal', alias='__typename'
    )


class GroupMutation(BaseModel):
    assignUser: Optional[DefaultResponse] = None
    create: Optional[GroupResponse] = None
    delete: Optional[DefaultResponse] = None
    unassignUser: Optional[DefaultResponse] = None
    update: Optional[DefaultResponse] = None
    typename__: Optional[Literal['GroupMutation']] = Field(
        'GroupMutation', alias='__typename'
    )


class GroupQuery(BaseModel):
    list: Optional[List[Optional[GroupMinimal]]] = None
    single: Optional[Group] = None
    typename__: Optional[Literal['GroupQuery']] = Field(
        'GroupQuery', alias='__typename'
    )


class GroupResponse(BaseModel):
    group: Optional[Group] = None
    responseResult: ResponseStatus
    typename__: Optional[Literal['GroupResponse']] = Field(
        'GroupResponse', alias='__typename'
    )


class KeyValuePair(BaseModel):
    """
    Generic Key Value Pair
    """

    key: String
    value: String
    typename__: Optional[Literal['KeyValuePair']] = Field(
        'KeyValuePair', alias='__typename'
    )


class LocalizationConfig(BaseModel):
    autoUpdate: Boolean
    locale: String
    namespaces: List[Optional[String]]
    namespacing: Boolean
    typename__: Optional[Literal['LocalizationConfig']] = Field(
        'LocalizationConfig', alias='__typename'
    )


class LocalizationLocale(BaseModel):
    availability: Int
    code: String
    createdAt: Date
    installDate: Optional[Date] = None
    isInstalled: Boolean
    isRTL: Boolean
    name: String
    nativeName: String
    updatedAt: Date
    typename__: Optional[Literal['LocalizationLocale']] = Field(
        'LocalizationLocale', alias='__typename'
    )


class LocalizationMutation(BaseModel):
    downloadLocale: Optional[DefaultResponse] = None
    updateLocale: Optional[DefaultResponse] = None
    typename__: Optional[Literal['LocalizationMutation']] = Field(
        'LocalizationMutation', alias='__typename'
    )


class LocalizationQuery(BaseModel):
    config: Optional[LocalizationConfig] = None
    locales: Optional[List[Optional[LocalizationLocale]]] = None
    translations: Optional[List[Optional[Translation]]] = None
    typename__: Optional[Literal['LocalizationQuery']] = Field(
        'LocalizationQuery', alias='__typename'
    )


class Logger(BaseModel):
    config: Optional[List[Optional[KeyValuePair]]] = None
    description: Optional[String] = None
    isEnabled: Boolean
    key: String
    level: Optional[String] = None
    logo: Optional[String] = None
    title: String
    website: Optional[String] = None
    typename__: Optional[Literal['Logger']] = Field('Logger', alias='__typename')


class LoggerTrailLine(BaseModel):
    level: String
    output: String
    timestamp: Date
    typename__: Optional[Literal['LoggerTrailLine']] = Field(
        'LoggerTrailLine', alias='__typename'
    )


class LoggingMutation(BaseModel):
    updateLoggers: Optional[DefaultResponse] = None
    typename__: Optional[Literal['LoggingMutation']] = Field(
        'LoggingMutation', alias='__typename'
    )


class LoggingQuery(BaseModel):
    loggers: Optional[List[Optional[Logger]]] = None
    typename__: Optional[Literal['LoggingQuery']] = Field(
        'LoggingQuery', alias='__typename'
    )


class MailConfig(BaseModel):
    dkimDomainName: Optional[String] = None
    dkimKeySelector: Optional[String] = None
    dkimPrivateKey: Optional[String] = None
    host: Optional[String] = None
    name: Optional[String] = None
    pass_: Optional[String] = Field(None, alias='pass')
    port: Optional[Int] = None
    secure: Optional[Boolean] = None
    senderEmail: Optional[String] = None
    senderName: Optional[String] = None
    useDKIM: Optional[Boolean] = None
    user: Optional[String] = None
    verifySSL: Optional[Boolean] = None
    typename__: Optional[Literal['MailConfig']] = Field(
        'MailConfig', alias='__typename'
    )


class MailMutation(BaseModel):
    sendTest: Optional[DefaultResponse] = None
    updateConfig: Optional[DefaultResponse] = None
    typename__: Optional[Literal['MailMutation']] = Field(
        'MailMutation', alias='__typename'
    )


class MailQuery(BaseModel):
    config: Optional[MailConfig] = None
    typename__: Optional[Literal['MailQuery']] = Field('MailQuery', alias='__typename')


class NavigationConfig(BaseModel):
    mode: NavigationMode
    typename__: Optional[Literal['NavigationConfig']] = Field(
        'NavigationConfig', alias='__typename'
    )


class NavigationItem(BaseModel):
    icon: Optional[String] = None
    id: String
    kind: String
    label: Optional[String] = None
    target: Optional[String] = None
    targetType: Optional[String] = None
    visibilityGroups: Optional[List[Optional[Int]]] = None
    visibilityMode: Optional[String] = None
    typename__: Optional[Literal['NavigationItem']] = Field(
        'NavigationItem', alias='__typename'
    )


class NavigationMutation(BaseModel):
    updateConfig: Optional[DefaultResponse] = None
    updateTree: Optional[DefaultResponse] = None
    typename__: Optional[Literal['NavigationMutation']] = Field(
        'NavigationMutation', alias='__typename'
    )


class NavigationQuery(BaseModel):
    config: NavigationConfig
    tree: List[Optional[NavigationTree]]
    typename__: Optional[Literal['NavigationQuery']] = Field(
        'NavigationQuery', alias='__typename'
    )


class NavigationTree(BaseModel):
    items: List[Optional[NavigationItem]]
    locale: String
    typename__: Optional[Literal['NavigationTree']] = Field(
        'NavigationTree', alias='__typename'
    )


class Page(BaseModel):
    authorEmail: String
    authorId: Int
    authorName: String
    content: String
    contentType: String
    createdAt: Date
    creatorEmail: String
    creatorId: Int
    creatorName: String
    description: String
    editor: String
    hash: String
    id: Int
    isPrivate: Boolean
    isPublished: Boolean
    locale: String
    path: String
    privateNS: Optional[String] = None
    publishEndDate: Date
    publishStartDate: Date
    render: Optional[String] = None
    scriptCss: Optional[String] = None
    scriptJs: Optional[String] = None
    tags: List[Optional[PageTag]]
    title: String
    toc: Optional[String] = None
    updatedAt: Date
    typename__: Optional[Literal['Page']] = Field('Page', alias='__typename')


class PageConflictLatest(BaseModel):
    authorId: String
    authorName: String
    content: String
    createdAt: Date
    description: String
    id: Int
    isPublished: Boolean
    locale: String
    path: String
    tags: Optional[List[Optional[String]]] = None
    title: String
    updatedAt: Date
    typename__: Optional[Literal['PageConflictLatest']] = Field(
        'PageConflictLatest', alias='__typename'
    )


class PageHistory(BaseModel):
    actionType: String
    authorId: Int
    authorName: String
    valueAfter: Optional[String] = None
    valueBefore: Optional[String] = None
    versionDate: Date
    versionId: Int
    typename__: Optional[Literal['PageHistory']] = Field(
        'PageHistory', alias='__typename'
    )


class PageHistoryResult(BaseModel):
    total: Int
    trail: Optional[List[Optional[PageHistory]]] = None
    typename__: Optional[Literal['PageHistoryResult']] = Field(
        'PageHistoryResult', alias='__typename'
    )


class PageLinkItem(BaseModel):
    id: Int
    links: List[Optional[String]]
    path: String
    title: String
    typename__: Optional[Literal['PageLinkItem']] = Field(
        'PageLinkItem', alias='__typename'
    )


class PageListItem(BaseModel):
    contentType: String
    createdAt: Date
    description: Optional[String] = None
    id: Int
    isPrivate: Boolean
    isPublished: Boolean
    locale: String
    path: String
    privateNS: Optional[String] = None
    tags: Optional[List[Optional[String]]] = None
    title: Optional[String] = None
    updatedAt: Date
    typename__: Optional[Literal['PageListItem']] = Field(
        'PageListItem', alias='__typename'
    )


class PageMigrationResponse(BaseModel):
    count: Optional[Int] = None
    responseResult: ResponseStatus
    typename__: Optional[Literal['PageMigrationResponse']] = Field(
        'PageMigrationResponse', alias='__typename'
    )


class PageMutation(BaseModel):
    convert: Optional[DefaultResponse] = None
    create: Optional[PageResponse] = None
    delete: Optional[DefaultResponse] = None
    deleteTag: Optional[DefaultResponse] = None
    flushCache: Optional[DefaultResponse] = None
    migrateToLocale: Optional[PageMigrationResponse] = None
    move: Optional[DefaultResponse] = None
    purgeHistory: Optional[DefaultResponse] = None
    rebuildTree: Optional[DefaultResponse] = None
    render: Optional[DefaultResponse] = None
    restore: Optional[DefaultResponse] = None
    update: Optional[PageResponse] = None
    updateTag: Optional[DefaultResponse] = None
    typename__: Optional[Literal['PageMutation']] = Field(
        'PageMutation', alias='__typename'
    )


class PageQuery(BaseModel):
    checkConflicts: Boolean
    conflictLatest: PageConflictLatest
    history: Optional[PageHistoryResult] = None
    links: Optional[List[Optional[PageLinkItem]]] = None
    list: List[PageListItem]
    search: PageSearchResponse
    searchTags: List[Optional[String]]
    single: Optional[Page] = None
    singleByPath: Optional[Page] = None
    tags: List[Optional[PageTag]]
    tree: Optional[List[Optional[PageTreeItem]]] = None
    version: Optional[PageVersion] = None
    typename__: Optional[Literal['PageQuery']] = Field('PageQuery', alias='__typename')


class PageResponse(BaseModel):
    page: Optional[Page] = None
    responseResult: ResponseStatus
    typename__: Optional[Literal['PageResponse']] = Field(
        'PageResponse', alias='__typename'
    )


class PageRule(BaseModel):
    deny: Boolean
    id: String
    locales: List[Optional[String]]
    match: PageRuleMatch
    path: String
    roles: List[Optional[String]]
    typename__: Optional[Literal['PageRule']] = Field('PageRule', alias='__typename')


class PageSearchResponse(BaseModel):
    results: List[Optional[PageSearchResult]]
    suggestions: List[Optional[String]]
    totalHits: Int
    typename__: Optional[Literal['PageSearchResponse']] = Field(
        'PageSearchResponse', alias='__typename'
    )


class PageSearchResult(BaseModel):
    description: String
    id: String
    locale: String
    path: String
    title: String
    typename__: Optional[Literal['PageSearchResult']] = Field(
        'PageSearchResult', alias='__typename'
    )


class PageTag(BaseModel):
    createdAt: Date
    id: Int
    tag: String
    title: Optional[String] = None
    updatedAt: Date
    typename__: Optional[Literal['PageTag']] = Field('PageTag', alias='__typename')


class PageTreeItem(BaseModel):
    depth: Int
    id: Int
    isFolder: Boolean
    isPrivate: Boolean
    locale: String
    pageId: Optional[Int] = None
    parent: Optional[Int] = None
    path: String
    privateNS: Optional[String] = None
    title: String
    typename__: Optional[Literal['PageTreeItem']] = Field(
        'PageTreeItem', alias='__typename'
    )


class PageVersion(BaseModel):
    action: String
    authorId: String
    authorName: String
    content: String
    contentType: String
    createdAt: Date
    description: String
    editor: String
    isPrivate: Boolean
    isPublished: Boolean
    locale: String
    pageId: Int
    path: String
    publishEndDate: Date
    publishStartDate: Date
    tags: List[Optional[String]]
    title: String
    versionDate: Date
    versionId: Int
    typename__: Optional[Literal['PageVersion']] = Field(
        'PageVersion', alias='__typename'
    )


class Renderer(BaseModel):
    config: Optional[List[Optional[KeyValuePair]]] = None
    dependsOn: Optional[String] = None
    description: Optional[String] = None
    icon: Optional[String] = None
    input: Optional[String] = None
    isEnabled: Boolean
    key: String
    output: Optional[String] = None
    title: String
    typename__: Optional[Literal['Renderer']] = Field('Renderer', alias='__typename')


class RenderingMutation(BaseModel):
    updateRenderers: Optional[DefaultResponse] = None
    typename__: Optional[Literal['RenderingMutation']] = Field(
        'RenderingMutation', alias='__typename'
    )


class RenderingQuery(BaseModel):
    renderers: Optional[List[Optional[Renderer]]] = None
    typename__: Optional[Literal['RenderingQuery']] = Field(
        'RenderingQuery', alias='__typename'
    )


class ResponseStatus(BaseModel):
    """
    Mutation Status
    """

    errorCode: Int
    message: Optional[String] = None
    slug: String
    succeeded: Boolean
    typename__: Optional[Literal['ResponseStatus']] = Field(
        'ResponseStatus', alias='__typename'
    )


class SearchEngine(BaseModel):
    config: Optional[List[Optional[KeyValuePair]]] = None
    description: Optional[String] = None
    isAvailable: Optional[Boolean] = None
    isEnabled: Boolean
    key: String
    logo: Optional[String] = None
    title: String
    website: Optional[String] = None
    typename__: Optional[Literal['SearchEngine']] = Field(
        'SearchEngine', alias='__typename'
    )


class SearchMutation(BaseModel):
    rebuildIndex: Optional[DefaultResponse] = None
    updateSearchEngines: Optional[DefaultResponse] = None
    typename__: Optional[Literal['SearchMutation']] = Field(
        'SearchMutation', alias='__typename'
    )


class SearchQuery(BaseModel):
    searchEngines: Optional[List[Optional[SearchEngine]]] = None
    typename__: Optional[Literal['SearchQuery']] = Field(
        'SearchQuery', alias='__typename'
    )


class SiteConfig(BaseModel):
    analyticsId: Optional[String] = None
    analyticsService: Optional[String] = None
    authAutoLogin: Optional[Boolean] = None
    authEnforce2FA: Optional[Boolean] = None
    authHideLocal: Optional[Boolean] = None
    authJwtAudience: Optional[String] = None
    authJwtExpiration: Optional[String] = None
    authJwtRenewablePeriod: Optional[String] = None
    authLoginBgUrl: Optional[String] = None
    company: Optional[String] = None
    contentLicense: Optional[String] = None
    description: Optional[String] = None
    editFab: Optional[Boolean] = None
    editMenuBar: Optional[Boolean] = None
    editMenuBtn: Optional[Boolean] = None
    editMenuExternalBtn: Optional[Boolean] = None
    editMenuExternalIcon: Optional[String] = None
    editMenuExternalName: Optional[String] = None
    editMenuExternalUrl: Optional[String] = None
    featurePageComments: Optional[Boolean] = None
    featurePageRatings: Optional[Boolean] = None
    featurePersonalWikis: Optional[Boolean] = None
    footerOverride: Optional[String] = None
    host: Optional[String] = None
    logoUrl: Optional[String] = None
    pageExtensions: Optional[String] = None
    robots: Optional[List[Optional[String]]] = None
    securityCSP: Optional[Boolean] = None
    securityCSPDirectives: Optional[String] = None
    securityHSTS: Optional[Boolean] = None
    securityHSTSDuration: Optional[Int] = None
    securityIframe: Optional[Boolean] = None
    securityOpenRedirect: Optional[Boolean] = None
    securityReferrerPolicy: Optional[Boolean] = None
    securitySRI: Optional[Boolean] = None
    securityTrustProxy: Optional[Boolean] = None
    title: Optional[String] = None
    uploadForceDownload: Optional[Boolean] = None
    uploadMaxFileSize: Optional[Int] = None
    uploadMaxFiles: Optional[Int] = None
    uploadScanSVG: Optional[Boolean] = None
    typename__: Optional[Literal['SiteConfig']] = Field(
        'SiteConfig', alias='__typename'
    )


class SiteMutation(BaseModel):
    updateConfig: Optional[DefaultResponse] = None
    typename__: Optional[Literal['SiteMutation']] = Field(
        'SiteMutation', alias='__typename'
    )


class SiteQuery(BaseModel):
    config: Optional[SiteConfig] = None
    typename__: Optional[Literal['SiteQuery']] = Field('SiteQuery', alias='__typename')


class StorageMutation(BaseModel):
    executeAction: Optional[DefaultResponse] = None
    updateTargets: Optional[DefaultResponse] = None
    typename__: Optional[Literal['StorageMutation']] = Field(
        'StorageMutation', alias='__typename'
    )


class StorageQuery(BaseModel):
    status: Optional[List[Optional[StorageStatus]]] = None
    targets: Optional[List[Optional[StorageTarget]]] = None
    typename__: Optional[Literal['StorageQuery']] = Field(
        'StorageQuery', alias='__typename'
    )


class StorageStatus(BaseModel):
    key: String
    lastAttempt: String
    message: String
    status: String
    title: String
    typename__: Optional[Literal['StorageStatus']] = Field(
        'StorageStatus', alias='__typename'
    )


class StorageTarget(BaseModel):
    actions: Optional[List[Optional[StorageTargetAction]]] = None
    config: Optional[List[Optional[KeyValuePair]]] = None
    description: Optional[String] = None
    hasSchedule: Boolean
    isAvailable: Boolean
    isEnabled: Boolean
    key: String
    logo: Optional[String] = None
    mode: Optional[String] = None
    supportedModes: Optional[List[Optional[String]]] = None
    syncInterval: Optional[String] = None
    syncIntervalDefault: Optional[String] = None
    title: String
    website: Optional[String] = None
    typename__: Optional[Literal['StorageTarget']] = Field(
        'StorageTarget', alias='__typename'
    )


class StorageTargetAction(BaseModel):
    handler: String
    hint: String
    label: String
    typename__: Optional[Literal['StorageTargetAction']] = Field(
        'StorageTargetAction', alias='__typename'
    )


class Subscription(BaseModel):
    """
    Subscriptions (Push, Real-time)
    """

    loggingLiveTrail: Optional[LoggerTrailLine] = None
    typename__: Optional[Literal['Subscription']] = Field(
        'Subscription', alias='__typename'
    )


class SystemExportStatus(BaseModel):
    message: Optional[String] = None
    progress: Optional[Int] = None
    startedAt: Optional[Date] = None
    status: Optional[String] = None
    typename__: Optional[Literal['SystemExportStatus']] = Field(
        'SystemExportStatus', alias='__typename'
    )


class SystemExtension(BaseModel):
    description: String
    isCompatible: Boolean
    isInstalled: Boolean
    key: String
    title: String
    typename__: Optional[Literal['SystemExtension']] = Field(
        'SystemExtension', alias='__typename'
    )


class SystemFlag(BaseModel):
    key: String
    value: Boolean
    typename__: Optional[Literal['SystemFlag']] = Field(
        'SystemFlag', alias='__typename'
    )


class SystemImportUsersResponse(BaseModel):
    failed: Optional[List[Optional[SystemImportUsersResponseFailed]]] = None
    groupsCount: Optional[Int] = None
    responseResult: Optional[ResponseStatus] = None
    usersCount: Optional[Int] = None
    typename__: Optional[Literal['SystemImportUsersResponse']] = Field(
        'SystemImportUsersResponse', alias='__typename'
    )


class SystemImportUsersResponseFailed(BaseModel):
    email: Optional[String] = None
    error: Optional[String] = None
    provider: Optional[String] = None
    typename__: Optional[Literal['SystemImportUsersResponseFailed']] = Field(
        'SystemImportUsersResponseFailed', alias='__typename'
    )


class SystemInfo(BaseModel):
    configFile: Optional[String] = None
    cpuCores: Optional[Int] = None
    currentVersion: Optional[String] = None
    dbHost: Optional[String] = None
    dbType: Optional[String] = None
    dbVersion: Optional[String] = None
    groupsTotal: Optional[Int] = None
    hostname: Optional[String] = None
    httpPort: Optional[Int] = None
    httpRedirection: Optional[Boolean] = None
    httpsPort: Optional[Int] = None
    latestVersion: Optional[String] = None
    latestVersionReleaseDate: Optional[Date] = None
    nodeVersion: Optional[String] = None
    operatingSystem: Optional[String] = None
    pagesTotal: Optional[Int] = None
    platform: Optional[String] = None
    ramTotal: Optional[String] = None
    sslDomain: Optional[String] = None
    sslExpirationDate: Optional[Date] = None
    sslProvider: Optional[String] = None
    sslStatus: Optional[String] = None
    sslSubscriberEmail: Optional[String] = None
    tagsTotal: Optional[Int] = None
    telemetry: Optional[Boolean] = None
    telemetryClientId: Optional[String] = None
    upgradeCapable: Optional[Boolean] = None
    usersTotal: Optional[Int] = None
    workingDirectory: Optional[String] = None
    typename__: Optional[Literal['SystemInfo']] = Field(
        'SystemInfo', alias='__typename'
    )


class SystemMutation(BaseModel):
    export: Optional[DefaultResponse] = None
    importUsersFromV1: Optional[SystemImportUsersResponse] = None
    performUpgrade: Optional[DefaultResponse] = None
    renewHTTPSCertificate: Optional[DefaultResponse] = None
    resetTelemetryClientId: Optional[DefaultResponse] = None
    setHTTPSRedirection: Optional[DefaultResponse] = None
    setTelemetry: Optional[DefaultResponse] = None
    updateFlags: Optional[DefaultResponse] = None
    typename__: Optional[Literal['SystemMutation']] = Field(
        'SystemMutation', alias='__typename'
    )


class SystemQuery(BaseModel):
    exportStatus: Optional[SystemExportStatus] = None
    extensions: Optional[List[Optional[SystemExtension]]] = None
    flags: Optional[List[Optional[SystemFlag]]] = None
    info: Optional[SystemInfo] = None
    typename__: Optional[Literal['SystemQuery']] = Field(
        'SystemQuery', alias='__typename'
    )


class ThemingConfig(BaseModel):
    darkMode: Boolean
    iconset: String
    injectBody: Optional[String] = None
    injectCSS: Optional[String] = None
    injectHead: Optional[String] = None
    theme: String
    tocPosition: Optional[String] = None
    typename__: Optional[Literal['ThemingConfig']] = Field(
        'ThemingConfig', alias='__typename'
    )


class ThemingMutation(BaseModel):
    setConfig: Optional[DefaultResponse] = None
    typename__: Optional[Literal['ThemingMutation']] = Field(
        'ThemingMutation', alias='__typename'
    )


class ThemingQuery(BaseModel):
    config: Optional[ThemingConfig] = None
    themes: Optional[List[Optional[ThemingTheme]]] = None
    typename__: Optional[Literal['ThemingQuery']] = Field(
        'ThemingQuery', alias='__typename'
    )


class ThemingTheme(BaseModel):
    author: Optional[String] = None
    key: Optional[String] = None
    title: Optional[String] = None
    typename__: Optional[Literal['ThemingTheme']] = Field(
        'ThemingTheme', alias='__typename'
    )


class Translation(BaseModel):
    key: String
    value: String
    typename__: Optional[Literal['Translation']] = Field(
        'Translation', alias='__typename'
    )


class User(BaseModel):
    appearance: String
    createdAt: Date
    dateFormat: String
    email: String
    groups: List[Optional[Group]]
    id: Int
    isActive: Boolean
    isSystem: Boolean
    isVerified: Boolean
    jobTitle: String
    lastLoginAt: Optional[Date] = None
    location: String
    name: String
    providerId: Optional[String] = None
    providerIs2FACapable: Optional[Boolean] = None
    providerKey: String
    providerName: Optional[String] = None
    tfaIsActive: Boolean
    timezone: String
    updatedAt: Date
    typename__: Optional[Literal['User']] = Field('User', alias='__typename')


class UserLastLogin(BaseModel):
    id: Int
    lastLoginAt: Date
    name: String
    typename__: Optional[Literal['UserLastLogin']] = Field(
        'UserLastLogin', alias='__typename'
    )


class UserMinimal(BaseModel):
    createdAt: Date
    email: String
    id: Int
    isActive: Boolean
    isSystem: Boolean
    lastLoginAt: Optional[Date] = None
    name: String
    providerKey: String
    typename__: Optional[Literal['UserMinimal']] = Field(
        'UserMinimal', alias='__typename'
    )


class UserMutation(BaseModel):
    activate: Optional[DefaultResponse] = None
    changePassword: Optional[UserTokenResponse] = None
    create: Optional[UserResponse] = None
    deactivate: Optional[DefaultResponse] = None
    delete: Optional[DefaultResponse] = None
    disableTFA: Optional[DefaultResponse] = None
    enableTFA: Optional[DefaultResponse] = None
    resetPassword: Optional[DefaultResponse] = None
    update: Optional[DefaultResponse] = None
    updateProfile: Optional[UserTokenResponse] = None
    verify: Optional[DefaultResponse] = None
    typename__: Optional[Literal['UserMutation']] = Field(
        'UserMutation', alias='__typename'
    )


class UserProfile(BaseModel):
    appearance: String
    createdAt: Date
    dateFormat: String
    email: String
    groups: List[Optional[String]]
    id: Int
    isSystem: Boolean
    isVerified: Boolean
    jobTitle: String
    lastLoginAt: Optional[Date] = None
    location: String
    name: String
    pagesTotal: Int
    providerKey: Optional[String] = None
    providerName: Optional[String] = None
    timezone: String
    updatedAt: Date
    typename__: Optional[Literal['UserProfile']] = Field(
        'UserProfile', alias='__typename'
    )


class UserQuery(BaseModel):
    lastLogins: Optional[List[Optional[UserLastLogin]]] = None
    list: Optional[List[Optional[UserMinimal]]] = None
    profile: Optional[UserProfile] = None
    search: Optional[List[Optional[UserMinimal]]] = None
    single: Optional[User] = None
    typename__: Optional[Literal['UserQuery']] = Field('UserQuery', alias='__typename')


class UserResponse(BaseModel):
    responseResult: ResponseStatus
    user: Optional[User] = None
    typename__: Optional[Literal['UserResponse']] = Field(
        'UserResponse', alias='__typename'
    )


class UserTokenResponse(BaseModel):
    jwt: Optional[String] = None
    responseResult: ResponseStatus
    typename__: Optional[Literal['UserTokenResponse']] = Field(
        'UserTokenResponse', alias='__typename'
    )


class AnalyticsProviderInput(BaseModel):
    """
    Analytics Configuration Input
    """

    config: Optional[List[Optional[KeyValuePairInput]]] = Field(
        None, description='Configuration values for this provider'
    )
    isEnabled: Boolean = Field(..., description='Is the provider active')
    key: String = Field(..., description='Unique identifier of the provider')
    typename__: Optional[Literal['AnalyticsProviderInput']] = Field(
        'AnalyticsProviderInput', alias='__typename'
    )


class AuthenticationStrategyInput(BaseModel):
    autoEnrollGroups: List[Optional[Int]]
    config: Optional[List[Optional[KeyValuePairInput]]] = None
    displayName: String
    domainWhitelist: List[Optional[String]]
    isEnabled: Boolean
    key: String
    order: Int
    selfRegistration: Boolean
    strategyKey: String
    typename__: Optional[Literal['AuthenticationStrategyInput']] = Field(
        'AuthenticationStrategyInput', alias='__typename'
    )


class CommentProviderInput(BaseModel):
    config: Optional[List[Optional[KeyValuePairInput]]] = None
    isEnabled: Boolean
    key: String
    typename__: Optional[Literal['CommentProviderInput']] = Field(
        'CommentProviderInput', alias='__typename'
    )


class KeyValuePairInput(BaseModel):
    """
    General Key Value Pair Input
    """

    key: String
    value: String
    typename__: Optional[Literal['KeyValuePairInput']] = Field(
        'KeyValuePairInput', alias='__typename'
    )


class LoggerInput(BaseModel):
    config: Optional[List[Optional[KeyValuePairInput]]] = None
    isEnabled: Boolean
    key: String
    level: String
    typename__: Optional[Literal['LoggerInput']] = Field(
        'LoggerInput', alias='__typename'
    )


class NavigationItemInput(BaseModel):
    icon: Optional[String] = None
    id: String
    kind: String
    label: Optional[String] = None
    target: Optional[String] = None
    targetType: Optional[String] = None
    visibilityGroups: Optional[List[Optional[Int]]] = None
    visibilityMode: Optional[String] = None
    typename__: Optional[Literal['NavigationItemInput']] = Field(
        'NavigationItemInput', alias='__typename'
    )


class NavigationTreeInput(BaseModel):
    items: List[Optional[NavigationItemInput]]
    locale: String
    typename__: Optional[Literal['NavigationTreeInput']] = Field(
        'NavigationTreeInput', alias='__typename'
    )


class PageRuleInput(BaseModel):
    deny: Boolean
    id: String
    locales: List[Optional[String]]
    match: PageRuleMatch
    path: String
    roles: List[Optional[String]]
    typename__: Optional[Literal['PageRuleInput']] = Field(
        'PageRuleInput', alias='__typename'
    )


class RendererInput(BaseModel):
    config: Optional[List[Optional[KeyValuePairInput]]] = None
    isEnabled: Boolean
    key: String
    typename__: Optional[Literal['RendererInput']] = Field(
        'RendererInput', alias='__typename'
    )


class SearchEngineInput(BaseModel):
    config: Optional[List[Optional[KeyValuePairInput]]] = None
    isEnabled: Boolean
    key: String
    typename__: Optional[Literal['SearchEngineInput']] = Field(
        'SearchEngineInput', alias='__typename'
    )


class StorageTargetInput(BaseModel):
    config: Optional[List[Optional[KeyValuePairInput]]] = None
    isEnabled: Boolean
    key: String
    mode: String
    syncInterval: Optional[String] = None
    typename__: Optional[Literal['StorageTargetInput']] = Field(
        'StorageTargetInput', alias='__typename'
    )


class SystemFlagInput(BaseModel):
    key: String
    value: Boolean
    typename__: Optional[Literal['SystemFlagInput']] = Field(
        'SystemFlagInput', alias='__typename'
    )
